image: klakegg/hugo:ext-ubuntu-ci

variables:
  HUGO_BASEURL: 'https://sosiristseng.gitlab.io/template-hugo-academic/'

test:
  script:
  - hugo -b ${HUGO_BASEURL}
  except:
  - main

pages:
  script:
  - apt-get update -qq && apt-get install gzip brotli -y
  - hugo --gc --minify -b ${HUGO_BASEURL}
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip   -f -k {} \; || echo 'Gzip failed. Skipping...'
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec brotli -f -k {} \; || echo 'Brotli failed. Skipping...'
  artifacts:
    paths:
    - public
  only:
  - main
