name: Auto update Go Mods

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # Every week

jobs:
  update-theme:
    runs-on: ubuntu-latest
    env:
      HUGO_BASEURL: 'https://sosiristseng.github.io/template-hugo-academic/'
    steps:
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Run update script
        run: bash ./update_wowchemy.sh
      - name: Build website
        run: hugo --gc --minify -b ${HUGO_BASEURL}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update Hugo mod" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
