name: github pages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_BASEURL: 'https://sosiristseng.github.io/template-hugo-academic/'
    steps:
    - uses: actions/checkout@v2
      # with:
      #  submodules: true  # Fetch Hugo themes (true OR recursive)
      #  fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - uses: actions/cache@v2
      with:
        path: /tmp/hugo_cache
        key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build website
      run: hugo --gc --minify -b $HUGO_BASEURL
    - name: Deploy website to Github pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force_orphan: true
        publish_dir: ./public

